version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  # conf.py 파일의 위치를 알려줍니다.
  # 만약 conf.py가 docs/conf.py 에 있다면 아래 경로를 docs/conf.py 로 고치세요.
  # 아까 'source' 폴더를 쓰셨으므로 아래가 맞을 확률이 높습니다.
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt